# Generated by Django 5.2.4 on 2025-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('nid', models.TextField()),
                ('nname', models.TextField()),
                ('nmobile', models.TextField()),
                ('naddress', models.TextField()),
            ],
            options={
                'db_table': 'tblAdoption',
            },
        ),
        migrations.CreateModel(
            name='ARequest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('aid', models.TextField()),
                ('description', models.TextField()),
                ('mid', models.TextField()),
                ('name', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('status', models.TextField()),
                ('nid', models.TextField()),
            ],
            options={
                'db_table': 'tblARequest',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'tblERegistration',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('vid', models.TextField()),
                ('name', models.TextField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'tblEvent',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('salary', models.TextField()),
                ('eid', models.TextField()),
                ('company', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'tblJob',
            },
        ),
        migrations.CreateModel(
            name='JRequest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('jid', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('salary', models.TextField()),
                ('eid', models.TextField()),
                ('company', models.TextField()),
                ('eemail', models.TextField()),
                ('emobile', models.TextField()),
                ('eaddress', models.TextField()),
                ('mid', models.TextField()),
                ('mname', models.TextField()),
                ('mmobile', models.TextField()),
                ('maddress', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'tblJRequest',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'tblMRegistration',
            },
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'tblNRegistration',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('vid', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tblVideo',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'tblVRegistration',
            },
        ),
    ]
